// PathOS Stage 7R — Regional Heatmap Data Loader
//
// Loads the four READY metric definitions + records generated by
// scripts/import-regional-data.py. The JSON files live under
// `frontend/generated/regional-data/` and are imported as static
// modules so Next.js bundles them at build time (no runtime fetch,
// no fixture fallback).
//
// IMPORTANT: These records are used for map exploration only. They do
// NOT influence Match Score, Assessment Score, or AI recommendations.

import recordsJson from "../../generated/regional-data/regional-records.json";
import metricsJson from "../../generated/regional-data/regional-metrics.json";
import datasetsJson from "../../generated/regional-data/regional-datasets.json";
import manifestJson from "../../generated/regional-data/regional-data-manifest.json";
import validationJson from "../../generated/regional-data/regional-data-validation.json";

import { REGIONAL_METRIC_IDS, type RegionalMetricId } from "./types";
import type {
  RegionalMetricDefinition,
  RegionalMetricRecord,
  RegionalDatasetMetadata,
  RegionalDataManifest,
  RegionalDataValidation,
} from "./types";

const records = recordsJson as unknown as { datasetId: string; records: RegionalMetricRecord[] };
const metricsDoc = metricsJson as unknown as { metrics: RegionalMetricDefinition[] };
const datasetsDoc = datasetsJson as unknown as RegionalDatasetMetadata;
const manifestDoc = manifestJson as unknown as RegionalDataManifest;
const validationDoc = validationJson as unknown as RegionalDataValidation;

/** Build a quick lookup: metricId → records[]. */
const recordsByMetric: Record<RegionalMetricId, RegionalMetricRecord[]> = {
  income: [],
  safety: [],
  employment: [],
  chinese_population: [],
};

for (const r of records.records) {
  if (!REGIONAL_METRIC_IDS.includes(r.metricId)) continue;
  recordsByMetric[r.metricId].push(r);
}

const definitionsByMetric: Record<RegionalMetricId, RegionalMetricDefinition | undefined> = {
  income: undefined,
  safety: undefined,
  employment: undefined,
  chinese_population: undefined,
};

for (const def of metricsDoc.metrics) {
  if (!REGIONAL_METRIC_IDS.includes(def.metricId)) continue;
  definitionsByMetric[def.metricId] = def;
}

export function getRegionalDatasetMetadata(): RegionalDatasetMetadata {
  return datasetsDoc;
}

export function getRegionalManifest(): RegionalDataManifest {
  return manifestDoc;
}

export function getRegionalValidation(): RegionalDataValidation {
  return validationDoc;
}

export function getRegionalMetricDefinition(metricId: RegionalMetricId): RegionalMetricDefinition | undefined {
  return definitionsByMetric[metricId];
}

export function getRegionalMetricRecords(metricId: RegionalMetricId): RegionalMetricRecord[] {
  return recordsByMetric[metricId] ?? [];
}

/** Convenience: lookup a single record (metric × geoId). */
export function findRegionalRecord(
  metricId: RegionalMetricId,
  geoId: string,
): RegionalMetricRecord | undefined {
  return recordsByMetric[metricId].find((r) => r.geoId === geoId);
}

/** Aggregate counters for UI / status panels. */
export interface RegionalCounters {
  readyMetricCount: number;
  blockedMetricCount: number;
  outOfScopeMetricCount: number;
  recordCount: number;
  verifiedCount: number;
  notReportedCount: number;
  partialCount: number;
  missingCount: number;
  coverage: string;
}

export function getRegionalCounters(): RegionalCounters {
  const s = validationDoc.summary;
  return {
    readyMetricCount: s.readyMetricCount,
    blockedMetricCount: validationDoc.blockedMetrics.length,
    outOfScopeMetricCount: validationDoc.outOfScopeMetrics.length,
    recordCount: s.recordsTotal,
    verifiedCount: s.recordsVerified,
    notReportedCount: s.recordsNotReported,
    partialCount: s.recordsPartial,
    missingCount: s.missingCount,
    coverage: s.coverage,
  };
}