// PathOS Stage 7R — Regional Heatmap Type Contracts
//
// Region data (state-level) is loaded from frontend/generated/regional-data/*
// which is generated by `scripts/import-regional-data.py` from the source
// workbook. This file declares the runtime shape; the JSON files must
// validate against these contracts.
//
// IMPORTANT: regional heatmap data is for *map exploration only* and must
// NOT influence Match Score / Assessment Score / AI recommendations. See
// `RegionalMetricDefinition.usedForMatch` — always `false` in this round.

export type RegionalMetricId =
  | "income"
  | "safety"
  | "employment"
  | "chinese_population";

export const REGIONAL_METRIC_IDS: readonly RegionalMetricId[] = [
  "income",
  "safety",
  "employment",
  "chinese_population",
] as const;

/** Raw direction: "direct" = higher raw is better; "inverse" = lower raw is better (e.g. crime rate). */
export type RawDirection = "direct" | "inverse";

export type VerificationStatus =
  | "verified"
  | "partial"
  | "user_provided_unverified"
  | "not_reported"
  | "not_applicable";

export interface RegionalDatasetMetadata {
  datasetId: string;
  datasetVersion: string;
  title: string;
  description: string;
  sourceName: string;
  sourceUrl: string;
  referenceYear: string;
  retrievedAt: string;
  geographyLevel: "state" | "county" | "place";
  geoIdType: "state_fips" | "county_fips" | "place_geoid";
  unit: string;
  valueDirection: string;
  normalizationMethod: string;
  coverage: string;
  status: VerificationStatus;
  productionReady: boolean;
  sourceWorkbookSha256: string;
  readyMetrics: RegionalMetricId[];
  existsOutOfScope: string[];
  blockedMetrics: string[];
}

/** Light / Dark palette: 5 stops each, plus a separate `missing` color. */
export interface PaletteStops {
  /** Hex colors from low to high (5 stops). */
  stops: readonly [string, string, string, string, string];
  /** Color used when the value is missing — must NOT equal the lowest stop. */
  missing: string;
  /** Outline color used on hover. */
  hoverOutline: string;
  /** Outline color used on selected. */
  selectedOutline: string;
}

export interface RegionalMetricDefinition {
  metricId: RegionalMetricId;
  displayNameZh: string;
  displayNameEn: string;
  shortDescription: string;
  longDescription: string;
  sourceName: string;
  sourceUrl: string;
  referenceYear: string;
  retrievedAt: string;
  geographyLevel: "state";
  geoIdType: "state_fips";
  rawUnit: string;
  displayUnit: string;
  higherIsBetter: boolean;
  rawDirection: RawDirection;
  normalizationMethod: string;
  allowedRange: readonly [number, number];
  paletteId: string;
  usedForMap: boolean;
  usedForMatch: false; // hard-coded false for this round
  verificationStatus: VerificationStatus;
  coverage: string;
  missingCount: number;
  datasetId: string;
}

export interface RegionalMetricRecord {
  metricId: RegionalMetricId;
  geoId: string; // 2-digit state FIPS with leading zero
  geoName: string;
  geoAbbr: string;
  geoNameEn: string;
  rawValue: number | null;
  displayValue: string | null;
  workbookNormalizedValue: number | null;
  /** Our normalized value in [0,1] where higher = better per the metric's intended semantics. */
  normalizedValue: number | null;
  referenceYear: string;
  sourceId: string;
  verificationStatus: VerificationStatus;
  missingReason: string | null;
  sourceSheet: string;
  sourceRow: number;
  sourceColumn: number;
  rawDirection: RawDirection;
}

/** Aggregated payload used by the runtime importer. */
export interface RegionalRecordsPayload {
  datasetId: string;
  records: RegionalMetricRecord[];
}

/** Manifest pointing at every generated artifact. */
export interface RegionalDataManifest {
  datasetId: string;
  manifestVersion: string;
  generatedAt: string;
  sourceWorkbook: {
    path: string;
    sha256: string;
  };
  artifacts: Array<{
    path: string;
    sha256: string;
    bytes: number;
  }>;
  totals: {
    metricCount: number;
    recordCount: number;
    readyMetricCount: number;
    blockedMetricCount: number;
    outOfScopeMetricCount: number;
  };
}

export interface RegionalDataValidation {
  datasetId: string;
  validatedAt: string;
  schemaVersion: string;
  summary: {
    readyMetricCount: number;
    recordsTotal: number;
    recordsVerified: number;
    recordsNotReported: number;
    recordsPartial: number;
    missingCount: number;
    coverage: string;
    duplicateGeoIds: number;
    outlierCount: number;
  };
  issues: Array<{
    severity: "critical" | "high" | "medium" | "low";
    code: string;
    [k: string]: unknown;
  }>;
  blockedMetrics: Array<{
    metricId: string;
    reason: string;
  }>;
  outOfScopeMetrics: string[];
  distribution: Array<{
    metricId: RegionalMetricId;
    count: number;
    min: number;
    max: number;
    mean: number;
    median: number;
    missingCount: number;
  }>;
}